### ISSUE TITLE
Exception thrown when trying to use 'select' : regex._regex_core.error: bad escape \d at position 7

### ISSUE THREAD

**Issue by jeremygaither** [flosell/trailscraper#407]
I receive the following error:

```bash
$ trailscraper select --use-cloudtrail-api --from '10 minutes ago' --to 'now'
Traceback (most recent call last):
  File "/usr/local/bin/trailscraper", line 33, in <module>
    sys.exit(load_entry_point('trailscraper==0.7.0', 'console_scripts', 'trailscraper')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/trailscraper/cli.py", line 91, in select
    from_date = time_utils.parse_human_readable_time(from_s)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/trailscraper/time_utils.py", line 7, in parse_human_readable_time
    return dateparser.parse(time_string, settings={'RETURN_AS_TIMEZONE_AWARE': True})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/conf.py", line 89, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/date.py", line 421, in get_date_data
    parsed_date = _DateLocaleParser.parse(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/date.py", line 178, in parse
    return instance._parse()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/languages/locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/languages/locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/dateparser/languages/locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/regex/regex.py", line 710, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/trailscraper/0.7.0_1/libexec/lib/python3.11/site-packages/regex/_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
```

I don't know if it is trying to parse the dates on the command line or not, but I've tried numbers ("10 minutes ago) and spelling the number ("ten minutes ago").

**Comment by flosell** [comment]
hi @jeremygaither, thanks for reporting this! I haven't had time to properly dig into this yet but a quick check trying to reproduce this makes me think this is probably related to Python 3.10 / 3.11 somehow. 
If you can, try downgrading to 3.9 and see if that fixes the issue. 

In any case, I'll try to make some time to see if I can get this fixed and support those versions properly. 

PRs are of course always welcome in case you are impatient :)

**Comment by flosell** [comment]
Closing this issue for now. If you are still seeing the issue on the new release, let me know and we'll reopen and reinvestigate)

**Comment by chenrui333** [comment]
I thought python 3.11 is part of the pipeline, why would that be an issue?

**Comment by chenrui333** [comment]
I dont quite see a reason of moving back to python@3.9, I have already updated the homebrew PR to use python@3.11 with some tweaks.

**Comment by flosell** [comment]
@chenrui333 ok with me!
